repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest tag from the repo
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Replace with the latest version of black
    hooks:
      - id: black
        language_version: python3  # Or your preferred version

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0  # Replace with the latest version of flake8
    hooks:
      - id: flake8
        additional_dependencies: []
